#!/usr/bin/env bash
# this script securely transfers file from a client to server

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# use the parameters with scp for the transfer
scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$ip":~/

