#!/usr/bin/env bash
# this script installs nginx as webserver on ubuntu machine

# install nginx
apt update -y
apt install -y nginx

# allow firewall connection on HTTP Port 80
ufw allow 'Nginx HTTP'

# create index.html to be used at root
echo "Hello World!" > index.html

# move the index.html to root folder
mv index.html /var/www/html

# restart nginx
/etc/init.d/nginx restart
# alternative restart
# service nginx restart
