#!/usr/bin/env bash
# this script installs nginx as webserver on ubuntu machine

# install nginx
apt update -y
apt install -y nginx

# allow firewall connection on HTTP Port 80
ufw allow 'Nginx HTTP'

# create index.html to be used at root
echo "Hello World!" > index.html

# move the index.html to root folder
mv index.html /var/www/html

# append redirection after server_name line
sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# restart nginx
service nginx restart
# older alternative for restart
#/etc/init.d/nginx restart
