#!/usr/bin/env bash
# This script manages the script 'manage_my_process'

file=/var/run/my_process.pid
program=./manage_my_process

if [ "$1" == "start" ]
then
	$program &
	echo $! > $file
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	pkill -f $program
	rm -f $file
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	pkill -f $program
        rm -f $file
	$program &
        echo $! > $file
        echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

