#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely & prints "I am invincible!!!" upon receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
