#!/usr/bin/env bash
# This script redirects home IP address and facebook.com

cp /etc/hosts ~/hosts.new
sed -i 's/^127.*\slocalhost/127.0.0.2	localhost/' ~/hosts.new
sed -i '1i\8.8.8.8	facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
